export const departmentOptions = [
    { value: "CAFAD", label: "College of Architecture, Fine Arts & Design" },
    { value: "CET", label: "College of Engineering Technology" },
    { value: "CICS", label: "College of Informatics and Computing Sciences" },
    { value: "COE", label: "College of Engineering" },
  ];
  
export const programOptions: Record<string, { value: string; label: string }[]> = {
  CAFAD: [
    { value: "BSArchi", label: "BS Architecture" },
    { value: "BFA", label: "Bachelor of Fine Arts" },
    { value: "BSID", label: "BS Interior Design" },
  ],
  CET: [
    { value: "BAET", label: "Bachelor of Automotive Engineering Technology" },
    { value: "BCVET", label: "Bachelor of Civil Engineering Technology" },
    { value: "BCPET", label: "Bachelor of Computer Engineering Technology" },
    { value: "BDET", label: "Bachelor of Drafting  Engineering Technology" },
    { value: "BEET", label: "Bachelor of Electrical Engineering Technology" },
    { value: "BELXET", label: "Bachelor of Electronics Engineering Technology" },
    { value: "BFET", label: "Bachelor of Food Engineering Technology" },
    { value: "BICET", label: "Bachelor of Instrumentation and Control Engineering Technology" },
    { value: "BMET", label: "Bachelor of Mechanical Engineering Technology" },
    { value: "BMXET", label: "Bachelor of Mechatronics Engineering Technology" },
    { value: "BWFET", label: "Bachelor of Welding and Fabrication Engineering Technology" },
    { value: "DTech", label: "Doctor of Technology" },
    { value: "MTech", label: "Master of Technology" }
  ],
  CICS: [
    { value: "BSCS", label: "BS Computer Science" },
    { value: "BSIT", label: "BS Information Technology" },
    { value: "MSCS", label: "MS Computer Science" },
    { value: "MSIT", label: "MS Information Technology" },
    { value: "MSDS", label: "MS Data Science" },
  ],
  COE: [
    { value: "BSAeE", label: "BS Aerospace Engineering" },
    { value: "BSAE", label: "BS Automotive Engineering" },
    { value: "BSBioE", label: "BS Biomedical Engineering" },
    { value: "BSCE", label: "BS Civil Engineering" },
    { value: "BSCerE", label: "BS Ceramics Engineering" },
    { value: "BSChE", label: "BS Chemical Engineering" },
    { value: "BSCoE", label: "BS Computer Engineering" },
    { value: "BSEE", label: "BS Electrical Engineering" },
    { value: "BSECE", label: "BS Electronics Engineering" },
    { value: "BSFE", label: "BS Food Engineering" },
    { value: "BSIE", label: "BS Industrial Engineering" },
    { value: "BSICE", label: "BS Instrumentation & Control Engineering" },
    { value: "BSME", label: "BS Mechanical Engineering" },
    { value: "BSMexE", label: "BS Mechatronics Engineering" },
    {value: "BSNAME", label: "BS Naval Architecture and Marine Engineering"},
    { value: "BSPetE", label: "BS Petroleum Engineering" },
    { value: "BSSE", label: "BS Sanitary Engineering" },
    { value: "BSTE", label: "BS Transportation Engineering" },
    { value: "BSGE", label: "BS Geodetic Engineering" },
    { value: "BSGeoE", label: "BS Geological Engineering" },
    { value: "BSMetE", label: "BS Metallurgical Engineering" },
    { value: "MEng", label: "Master of Engineering" },
    { value: "MSAI", label: "MS Artificial Intelligence" },
    { value: "MSAM", label: "MS Advanced Manufacturing" },
    { value: "MSCE", label: "MS Computer Engineering" },
    { value: "MSCM", label: "MS Construction Management" },
    { value: "MSDS", label: "MS Data Science" },
    { value: "MSEaE", label: "MS Earthquake Engineering" },
    { value: "MSECE", label: "MS Electronics Engineering" },
    { value: "MSEgyE", label: "MS Energy Engineering" },
    { value: "MSEM", label: "MS Engineering Management" },
    { value: "MSTE", label: "MS in Transportation Engineering" },
    { value: "MSMSE", label: "MS Material Science and Engineering" },
    { value: "MUPD", label: "Master in Urban Planning and Design" },
    { value: "PhDECE", label: "Doctor of Philosophy in Electronics Engineering" },
    { value: "PhDEM", label: "Doctor of Philosophy in Engineering Management" },
    { value: "PhDEE", label: "Doctor of Philosophy in Engineering Education" }
  ],
};