name: Production

on:
  workflow_run:
    workflows: ["Backend_CI", "Frontend_CI"]
    types:
      - completed
  pull_request:
    branches:
      - main  # This is the 'Production' branch you're targeting for PRs

jobs:
  liquibase_migration:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Set up Java (required by Liquibase)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      # Step 2: Install Liquibase
      - name: Install liquibase
        run: |
          # Download the Liquibase tarball
          wget https://github.com/liquibase/liquibase/releases/download/v4.21.0/liquibase-4.21.0.tar.gz
          
          # Ensure the file is downloaded
          ls -l liquibase-4.21.0.tar.gz
          
          # Extract the tarball into the current directory
          tar -xvf liquibase-4.21.0.tar.gz
          
          # List the extracted files in the current directory to inspect the structure
          ls -l liquibase-4.21.0/

          # Move the liquibase binary to /usr/local/bin if it exists
          if [ -f liquibase-4.21.0/liquibase ]; then
            sudo mv liquibase-4.21.0/liquibase /usr/local/bin/
          else
            echo "Liquibase binary not found! Check extraction steps."
            exit 1
          fi

      # Step 3: Generate changelog from dev database
      - name: Generate changelog from dev database
        run: liquibase --defaultsFile=liquibase.dev.properties generateChangeLog
        working-directory: ./migration  # Ensure this directory contains your Liquibase files

      # Step 4: Update migration to prod database
      - name: Update migration to prod database
        run: liquibase --defaultsFile=liquibase.prod.properties update
        working-directory: ./migration  # Ensure this directory contains your Liquibase files