name: Production

on:
  workflow_run:
    workflows: ["Backend_CI", "Frontend_CI"]
    types:
      - completed
  pull_request:
    branches:
      - main  # This is the 'Production' branch you're targeting for PRs

jobs:
  liquibase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Generate diff"
        uses: liquibase-github-actions/diff-changelog@v4.30.0
        with:
          changelogFile: "db/changelog/${{ github.run_id }}-db.changelog-master.sql"
          referenceUrl: ${{ secrets.DB_DEV_URL }}
          url: ${{ secrets.DB_PROD_URL }}
          referenceUsername: ${{ secrets.DB_PROD_USERNAME }}
          referencePassword: ${{ secrets.DB_PROD_PASSWORD }}
          username: ${{ secrets.DB_PROD_USERNAME }}
          password: ${{ secrets.DB_PROD_PASSWORD }}

      - name: "Migrate to prod"
        uses: liquibase-github-actions/update@v4.30.0
        with:
          changelogFile: "db/changelog/${{ github.run_id }}-db.changelog-master.sql"
          url: ${{ secrets.DB_PROD_URL }}
          username: ${{ secrets.DB_PROD_USERNAME }}
          password: ${{ secrets.DB_PROD_PASSWORD }}