name: Production

on:
  workflow_run:
    workflows: ["Backend_CI", "Frontend_CI"]
    types:
      - completed
  pull_request:
    branches:
      - main  # This is the 'Production' branch you're targeting for PRs

jobs:
  liquibase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: "Generate dev changelog"
      #   uses: liquibase-github-actions/generate-changelog@v4.30.0
      #   with:
      #     changelogFile: "db/changelog/${{ github.run_id }}-db-dev.changelog-master.sql"
      #     url: ${{ secrets.DB_DEV_URL }}
      #     username: ${{ secrets.DB_DEV_USERNAME }}
      #     password: ${{ secrets.DB_DEV_PASSWORD }}
      # - name: "Generate prod changelog"
      #   uses: liquibase-github-actions/generate-changelog@v4.30.0
      #   with:
      #     changelogFile: "db/changelog/${{ github.run_id }}-db-prod.changelog-master.sql"
      #     url: ${{ secrets.DB_PROD_URL }}
      #     username: ${{ secrets.DB_PROD_USERNAME }}
      #     password: ${{ secrets.DB_PROD_PASSWORD }}
      - name: "Generate diff"
        uses: liquibase-github-actions/diff-changelog@v4.30.0
        with:
          changelogFile: "db/changelog/${{ github.run_id }}-db-prod.changelog-master.sql"
          referenceUrl: "jdbc:postgresql://frames_dev:nc8qQXku0PJU@ep-misty-brook-a1ejqloe.ap-southeast-1.aws.neon.tech/frames?sslmode=require"
          url: "jdbc:postgresql://admin:SmsrLv9tdY3a@ep-misty-brook-a1ejqloe.ap-southeast-1.aws.neon.tech/frames_prod?sslmode=require"

      - name: "Migrate to prod"
        uses: liquibase-github-actions/update@v4.30.0
        with:
          changelogFile: "db/changelog/${{ github.run_id }}-db.changelog-master.sql"
          url: ${{ secrets.DB_PROD_URL }}
          username: ${{ secrets.DB_PROD_USERNAME }}
          password: ${{ secrets.DB_PROD_PASSWORD }}