name: Production

on:
  workflow_run:
    workflows: ["Backend_CI", "Frontend_CI"]
    types:
      - completed
  pull_request:
    branches:
      - main  # This is the 'Production' branch you're targeting for PRs

jobs:
  liquibase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: liquibase-github-actions/generate-changelog@v4.30.0
        with:
          url: "jdbc:postgresql://ep-misty-brook-a1ejqloe.ap-southeast-1.aws.neon.tech:5432/frames"
          dataOutputDirectory: "db/changelog/"