name: Production

on:
  workflow_run:
    workflows: ["Backend_CI", "Frontend_CI"]  # Name of the backend workflow
    types:
      - completed  # Ensure it only runs when the backend pipeline completes
  push:
    branches:
      - main  # Trigger only when a commit is pushed to the `main` branch
jobs:
  Migration:
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Install liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.21.0/liquibase-4.21.0.tar.gz
          tar -xvf liquibase-4.21.0.tar.gz
          sudo mv liquibase-4.21.0/liquibase /usr/local/bin/

      - name: Generate changelog from dev database
        run: liquibase --defaultsFile=liquibase.dev.properties generateChangeLog
        working-directory: ./migration  

      - name: Update migration to prod database
        run: liquibase --defaultsFile=liquibase.prod.properties update
        working-directory: ./migration  
