name: Production

on:
  workflow_run:
    workflows: ["Backend_CI", "Frontend_CI"]
    types:
      - completed
  pull_request:
    branches:
      - main  # This is the 'Production' branch you're targeting for PRs

jobs:
  Migration:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install liquibase
        run: |
          wget https://github.com/liquibase/liquibase/releases/download/v4.21.0/liquibase-4.21.0.tar.gz
          tar -xvf liquibase-4.21.0.tar.gz
          sudo mv liquibase-4.21.0/liquibase /usr/local/bin/

      - name: Generate changelog from dev database
        run: liquibase --defaultsFile=liquibase.dev.properties generateChangeLog
        working-directory: ./migration  

      - name: Update migration to prod database
        run: liquibase --defaultsFile=liquibase.prod.properties update
        working-directory: ./migration
